In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr1.shape

(5,)

In [5]:
arr1.ndim

1

In [3]:
import numpy as np

arr2=np.linspace(1,10,5)

In [5]:
arr2=np.linspace(1,10,5)
arr2

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [6]:
arr2.shape

(5,)

In [7]:
arr2.ndim

1

In [22]:
def lin(a,b,c):
    d=(b-a)/(c-1)
    array=[]
    for num in range(0,c):
        array.append(a+num*d)
        
    return array
    

In [23]:
lin(1,10,5)

[1.0, 3.25, 5.5, 7.75, 10.0]

In [17]:
lin(1,10,10)

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]

In [18]:
import numpy as np


In [19]:
ar=np.array([1,2,3,4,5])
ar

array([1, 2, 3, 4, 5])

In [24]:
len(ar,)

5

In [25]:
ar2=np.array([[[1,2],[3,4],[5,6],[7,8]]])
ar2

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [26]:
ar2.shape

(1, 4, 2)

In [27]:
len(ar2)

1

In [28]:
ar2.ndim

3

In [66]:
ar3=np.array([[[1,2,3],[7,8,9]],[[4,5,6],[3,5,7]]])
ar3

array([[[1, 2, 3],
        [7, 8, 9]],

       [[4, 5, 6],
        [3, 5, 7]]])

In [67]:
ar3.shape

(2, 2, 3)

In [68]:
ar3.ndim

3

In [69]:
len(ar3),len(ar3[0])

(2, 2)

In [59]:
ar4=np.array([1,2,3,4])
ar4

array([1, 2, 3, 4])

In [63]:
len(ar4)

4

In [61]:
ar4.shape

(4,)

In [70]:
ar3.size

12

In [71]:
ar3.itemsize

4

In [72]:
ar4.itemsize

4

In [73]:
ar4.dtype

dtype('int32')

In [74]:
ar3.dtype

dtype('int32')

In [1]:
import numpy as np

In [2]:
arr=np.arange(40).reshape(8,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [13]:
arr[:,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22],
       [26, 27],
       [31, 32],
       [36, 37]])

In [1]:
import numpy as np

In [2]:
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [18]:
arr2=np.arange(40).reshape(8,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [19]:
arr2[2:3]

array([[10, 11, 12, 13, 14]])

In [20]:
arr2[: , 0]

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [21]:
arr2[:8, ::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [22]:
arr2[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [23]:
arr2[::3,::2]

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [29]:
N=np.random.randint(low=1,high=10000,size=10).reshape(2,5)
N

array([[2444, 7370, 1457, 1932, 3945],
       [4823, 5202, 5922,  132,  271]])

In [30]:
N=(N-N.min())/(N.max()-N.min())
N

array([[0.31942526, 1.        , 0.18306162, 0.24868748, 0.52680298],
       [0.64810721, 0.70046974, 0.79994474, 0.        , 0.0192042 ]])

In [55]:
def maximum(array,n):
    if(n>len((array))):
        print("n out of bound")
    else:
        array.sort()
        return arr[len(array).n]


In [58]:
arr9=np.array([1,5,2,9,6,8])

In [59]:
maximum(arr9,10)

n out of bound


In [62]:
list1=np.array([1,1,1,[1],1,1,[1],1])
list2=np.array([1,1,1,[],1,1,[],1])
list1==[1]


array([ True,  True,  True, False,  True,  True, False,  True])

In [63]:
list2==[]

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [64]:
[x==[] for x in list2]

[False, False, False, True, False, False, True, False]

In [72]:
def element(array):
     return array.ndim and array.size
element(np.array(None))


0

In [69]:
element(np.array([]))

0

In [73]:
element(np.zeros((2,3,4)))

24

In [1]:
arr1=np.array([[1,2,3],[4,5,6]])
def shape(arr1):
    print((arr1.ndim,int(arr1.size/arr.ndim)))
    shape(arr1)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [45]:
arr1=np.array([[1,2,3],[4,5,6]])
def shape(arr1):
    print((arr1.ndim,int(arr1.size/arr.ndim)))
    shape(arr1)
    

In [53]:
arr1=np.arange(20).reshape(4,5)
arr1


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:

arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [55]:
temp=arr1[:,0]
arr1[:,0]=arr1[:,1]
arr1[:,1]=temp
arr1

array([[ 1,  1,  2,  3,  4],
       [ 6,  6,  7,  8,  9],
       [11, 11, 12, 13, 14],
       [16, 16, 17, 18, 19]])

arr1

In [69]:
arr2=np.arange(20).reshape(4,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
def swapcolumn(arr,frm,to):
    arr[:,[frm,to]]=arr[:,[to,frm]]
    swaapcolumn(arr2,0,3)
    print(arr2)

In [75]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])